import React from 'react';
import "./App.css";

export default function Terms() {
    return (
        <div className="legal-container">
            <h1 className="legal-title">Terms & Conditions</h1>
            <div className="legal-body">
                <p>These Raven (or Raven Platform) Terms and Conditions (“Terms of Use”, “Terms”) are entered into between Moonshot Investment Corp (#1, Advanced Tower, Panama City, Panama) (referred to as “Company”, “we”, “our” and “us”) and you or the company or other legal entity that you represent. (“you” or “your”)</p>

                <p>Please read these Terms of Use carefully, as they govern your use of Raven (or Raven Platform) (referred to as the “Platform”), as well as any other services provided by us (“Services”). By accessing or using the Platform or any of its Services, you agree to comply with these Terms of Use. If you do not agree to these Terms, you must not access or use the Platform.</p>

                <p>Due to the nature of the Platform, access to and use of the Platform is not intended for individuals or entities located in, or accessing from, certain restricted jurisdictions, including but not limited to Crimea, Donetsk and Luhansk, Cuba, Democratic People’s Republic of Korea, Democratic Republic of the Congo, Islamic Republic of Iran, Libya, People’s Republic of China, Republic of Belarus, Russian Federation, Somalia, South Sudan, Sudan, Syria, United States of America, as well as any other territories subject to comprehensive sanctions under United States law or international sanctions. Additionally, the Platform is not intended for use by individuals or entities listed on any sanctions list maintained by the United States Office of Foreign Assets Control, the United Nations, or other applicable authorities. You are responsible for verifying that they do not fall under such restrictions before accessing the Platform.</p>

                <p>We reserve the right to modify these Terms at any time. Such modifications will be effective immediately upon posting the updated Terms on our website. Continued use of the Platform or Services after any such changes constitutes your acceptance of the new Terms. You are expected to check this page frequently so you are aware of any changes, as they are binding on you.</p>

                <h2>1. The Raven (or Raven Platform)</h2>
                <p>The Platform provides a web-based or mobile-accessible interface enabling interaction with a decentralised protocol operating on various public blockchains, facilitating the transfer or exchange of compatible digital assets across different public blockchains.</p>
                <p>Access to the Platform requires the use of non-custodial wallet software that enables interaction with public blockchains. Your relationship with the provider of such non-custodial wallet software is governed exclusively by the terms and conditions applicable to that wallet provider. The Platform does not exercise custody, control, or authority over the contents of your wallet, nor does it have the capability to retrieve, manage, or transfer its contents.</p>

                <h2>2. User Eligibility</h2>
                <p>To use the Platform, you must be at least 18 years old and reside in a jurisdiction where the use of the Platform is legal.</p>
                <p>You must provide all required information and documents during the account opening process and keep this information updated. We may request additional information at any time, and failure to provide this may result in restricted access to your account.</p>
                <p>Additional eligibility requirements may apply based on your location and the applicable laws. We reserve the right to refuse service, terminate accounts, or limit access to Platform at our sole discretion.</p>

                <h2>3. User Obligations</h2>
                <p>You are solely responsible for your use of the Platform, including the transfer, exchange, or interaction with digital assets across different public blockchains. You agree to use the Platform in compliance with all applicable laws, regulations, and these Terms.</p>
                <p>You are responsible for the security and management of your wallet, private keys, key shares, seed phrases, passwords, or any other credentials linked to your blockchain addresses. The Platform bears no liability for any unauthorised access, loss, or misuse of your wallet or blockchain addresses, and any such incidents remain your sole responsibility.</p>
                <p>You must take appropriate security measures to protect your wallet and credentials, including using strong and unique passwords, regularly updating wallet software, and ensuring that your private keys, seed phrases, or other sensitive information are not shared with anyone. Any loss or damage resulting from your failure to maintain the confidentiality of your credentials shall be your responsibility.</p>
                <p>You agree to notify us immediately if you become aware of or suspect any unauthorised access, security breaches, or misuse of your wallet or blockchain addresses in connection with the Platform.</p>
                <p>You are responsible for providing accurate, complete, and up-to-date information when interacting with the Platform or responding to verification requests. Failure to provide accurate or truthful information may result in restricted or terminated access to the Platform.</p>
                <p>In certain circumstances, we may require additional information or documentation from you to comply with applicable laws, regulations, or requests from government authorities. You agree to provide any requested documentation promptly and accurately. Failure to comply with such requests may result in the suspension or termination of your access to the Platform.</p>

                <h2>4. Fees and Charges</h2>
                <p>The use of the Platform may involve certain fees, including but not limited to transaction fees, service fees, gas fees, and currency conversion fees if applicable. Detailed information about these fees will be provided within the Platform and may be subject to change.</p>
                <p>Each blockchain may require the payment of a transaction fee (a “Gas Fee”) for every transaction that occurs on such blockchain, with such Gas Fee to be based on the structure and composition of the respective Blockchain. This means that you may need to pay a Gas Fee for each transaction that occurs via the Services. Gas Fees may vary based on market conditions on the applicable blockchain.</p>
                <p>When you undertake a transaction involving digital assets (“Digital Assets”), including cryptographic assets, virtual currencies, tokens, stablecoins, or any other digital representation of value based on blockchain or distributed ledger technology, you may be subject to additional terms and conditions imposed by the respective third party or digital asset provider (“Digital Asset Terms”). You agree that you have read, understood, and agreed to be bound by any applicable Digital Asset Terms governing your interaction with, or the sale or purchase of, the respective Digital Asset.</p>
                <p>From time to time, the Platform may provide options to receive payment processing and related services from decentralised application providers or third-party service providers (“Third Party Service Providers”). Your use of the Service, and any payment processing and related services provided by a Third Party Service Provider, is subject to your agreement(s) with such Third Party Service Providers for such Service and payment processing and related services, as may be modified by the Third Party Service Providers from time to time. You must comply with the third-party service provider agreement as you may lose access to the Service in instances where you breach such agreement. We are unable to reverse or reimburse transactions and have no control over third-party payment processing providers.</p>
                <p>All fees paid to the Platform are non-refundable, except as required by applicable law. You are solely responsible for ensuring the accuracy of any payment details and transaction information. The Platform shall not be held liable for any fees incurred due to errors in transaction details, including but not limited to incorrect wallet addresses or insufficient gas fees.</p>
                <p>We reserve the right to modify, update, or introduce new fees at our sole discretion. Any changes to the fee structure will be communicated to you through the Platform or other appropriate means. Continued use of the Platform after such changes are implemented constitutes your acceptance of the updated fee structure.</p>
                <p>In relation to transactions and payments made under these Terms, you are responsible for identifying and paying any taxes and other governmental fees and charges, including penalties and interest. Unless otherwise noted, all fees payable by you are exclusive of taxes, and we reserve the right to withhold taxes where required.</p>

                <h2>5. Risks Associated with Cryptocurrencies</h2>
                <p>Before using any of our Services, it's important to be aware of potential risks. These risks, which may be significant and potentially devastating, are outlined as a non-exhaustive list in Annexure A, however, there may be others that could arise in the future. Before you use the Platform or our Services, it is important that you carefully evaluate whether using our Platform or our Services is suitable for you based on your financial situation. We recommend that you seek professional financial advice before using our Services. By using our Services, you acknowledge and accept the risks set out in Annexure A.</p>

                <h2>6. Prohibited uses</h2>
                <p>In addition to other prohibitions as set out in these Terms of Use, you are prohibited from using the Platform or its content:</p>
                <ul>
                    <li>for any unlawful purpose;</li>
                    <li>to solicit others to perform or participate in any unlawful acts;</li>
                    <li>to violate any international, federal, provincial or State regulations, rules, laws, or local ordinances;</li>
                    <li>to infringe upon or violate our intellectual property rights or the intellectual property rights of others;</li>
                    <li>to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Platform or of any related website, other websites, or the internet;</li>
                    <li>to collect or track the personal information of others;</li>
                    <li>to manipulate trading markets through tactics such as "rug pulls," wash trading, spoofing, or other fraudulent schemes in violation of applicable laws or regulations;</li>
                    <li>to buy, sell, or transfer stolen or unauthorised items, or to transact digital assets derived from criminal or fraudulent activity;</li>
                    <li>to transfer or use digital assets unless you are the rightful owner or are authorised to act on their behalf; or</li>
                    <li>to interfere with or circumvent the security features of the Platform or any related website, other websites, or the internet.</li>
                </ul>
                <p>We reserve the right to terminate your use of the Platform or any related website for violating any of the prohibited uses.</p>

                <h2>7. Optional tools</h2>
                <p>We may provide you with access to third-party tools over which we neither monitor nor have any control nor input.</p>
                <p>You acknowledge and agree that we provide access to such tools "as is" and "as available" without any warranties, representations or conditions of any kind and without any endorsement. We will have no liability whatsoever arising from or relating to your use of optional third-party tools.</p>
                <p>Any use by you of optional tools offered through the Platform is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s).</p>
                <p>We may also, in the future, offer new services and/or features through the Platform (including the release of new tools and resources). Such new features and/or services will also be subject to these Terms of Use.</p>

                <h2>8. Third-Party Services</h2>
                <p>Our Platform may incorporate or provide links to resources and services operated by third parties, including advertisements, banners, and sponsored content (“Third-Party Services”). These Third-Party Services are offered for your convenience, and their presence on our Platform does not imply endorsement or recommendation. As independently operated resources, Third-Party Services are outside of our control and not considered part of our Services.</p>
                <p>When you engage with Third-Party Services on our Platform, you acknowledge and grant us permission to share relevant information with these providers to facilitate the use of integrated features. However, we assume no responsibility or liability for any issues arising from your use of Third-Party Services. Each third-party provider is solely responsible for its services and may have distinct terms and conditions governing their use. It is your responsibility to review and agree to these terms before engaging with Third-Party Services, as we make no guarantees and assume no liability for the actions or omissions of these external providers.</p>

                <h2>9. No Investment Advice</h2>
                <p>The information provided through the Platform is for general informational purposes only and should not be construed as investment advice. We do not provide personalised investment recommendations or advice regarding the suitability of any investment. You should consult with a qualified financial advisor before making any investment decisions.</p>

                <h2>10. No Securities or Brokerage Services</h2>
                <p>We are not registered with the United States Securities and Exchange Commission (SEC) as a national securities exchange or in any other capacity. You acknowledge and agree that we do not act as a broker or intermediary for the submission or execution of trading orders on your behalf. Additionally, we do not facilitate the execution or settlement of transactions, which are conducted entirely on public distributed blockchains.</p>

                <h2>11. Accuracy, completeness and timeliness of information</h2>
                <p>We are not responsible if information made available on the Platform is not accurate, complete or current. The material on the Platform is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on the Platform is at your own risk.</p>
                <p>This Platform may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this Platform at any time, but we have no obligation to update any information on our Platform. You agree that it is your responsibility to monitor changes to our Platform.</p>

                <h2>12. User comments, feedback and other submissions</h2>
                <p>If, at our request, you send certain specific submissions or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise("comments"), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and will be under no obligation:</p>
                <ol>
                    <li>to maintain any comments in confidence;</li>
                    <li>to pay compensation for any comments; or</li>
                    <li>to respond to any comments.</li>
                </ol>
                <p>We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion is unlawful, offensive, threatening, libellous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms of Use.</p>
                <p>You agree that your comments will not violate any right of any third-party, including copyright, trade mark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libellous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Platform or any related website.</p>
                <p>You may not use a false email address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party.</p>

                <h2>13. Intellectual Property Rights</h2>
                <p>We are the creators and rightful owners of the Platform. All logos, trademarks, designs, text, photos, videos, software, computer programs, code, and other content associated with the Platform, including but not limited to the design, structure, selection, coordination, expression, ‘look and feel,’ and arrangement of such content—are owned, controlled, or licensed by us and are protected under copyright, patent, and trademark laws, as well as other applicable intellectual property rights. We retain exclusive ownership of our intellectual property and reserve the right to use it as we deem appropriate.</p>
                <p>Any third-party trademarks, logos, articles, text, photos, videos, and other content available on the Platform remain the property of their respective owners. No user may use the trademarks, logos, or any other intellectual property displayed on our Platform without prior written consent from us or the respective owners. Certain features, functionalities, and portions of the Platform may also be protected under our patent applications or granted patents</p>

                <h2>14. Errors, inaccuracies and omissions</h2>
                <p>Occasionally, there may be information on our Platform that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Platform is inaccurate at any time without prior notice (including after you have submitted your order).</p>
                <p>We undertake no obligation to update, amend or clarify information in the Platform, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Platform should be taken to indicate that all information in the Platform has been modified or updated.</p>

                <h2>15. Personal information</h2>
                <p>Your submission of personal information through the Platform is governed by our Privacy Policy.</p>

                <h2>16. Disclaimer of warranties and limitation of liability</h2>
                <p>We do not guarantee, represent or warrant that your use of our Platform will be uninterrupted, timely, secure or error-free.</p>
                <p>We do not warrant that the results that may be obtained from the use of the Platform will be accurate or reliable.</p>
                <p>You agree that from time to time we may modify the Platform for indefinite periods of time or cancel the Services at any time, without notice to you.</p>
                <p>You expressly agree that your use of, or inability to use, the Platform is at your sole risk. The Platform and all products and services delivered to you through the Services are (except as expressly stated by us or if cannot be excluded by law) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.</p>
                <p>We make no guarantees regarding the performance, security, or compatibility of any assets, blockchains, or third-party tools used in connection with the Platform.</p>
                <p>The Platform supports only certain tokens or digital assets. Attempting to transfer unsupported tokens or assets via the Platform may result in loss or failure of the transaction. You are solely responsible for ensuring that all tokens you transfer are supported and compliant with the Platform’s requirements.</p>
                <p>Blockchain networks may undergo forks, upgrades, or other protocol changes that could disrupt or impact the functionality of the Platform. We are not responsible for any losses or interruptions caused by such events.</p>
                <p>The Platform does not guarantee the preservation of the value of any digital assets transferred through it. You acknowledge that the value of digital assets may fluctuate significantly due to market conditions or other factors beyond our control. We are not responsible for any losses resulting from changes in asset values.</p>
                <p>IN NO EVENT WILL Raven (or Raven Platform), INCLUDING OUR AFFILIATES, SUBSIDIARIES, PARENTS, SUCCESSORS, AND ASSIGNS, AND EACH OF OUR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR SHAREHOLDERS (COLLECTIVELY “Raven (or Raven Platform)” FOR PURPOSES OF THIS SECTION), BE LIABLE TO YOU FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, CONSEQUENTIAL, OR INDIRECT DAMAGES (INCLUDING DAMAGES FOR DELETION, CORRUPTION, LOSS OF DATA, LOSS OF PROGRAMS, FAILURE TO STORE ANY INFORMATION OR OTHER CONTENT MAINTAINED OR TRANSMITTED BY THE Raven (or Raven Platform) PLATFORM, SERVICE INTERRUPTIONS, OR FOR THE COST OF PROCUREMENT OF SUBSTITUTE SERVICES) ARISING OUT OF OR IN CONNECTION WITH THE Raven (or Raven Platform) PLATFORM, Raven (or Raven Platform) SERVICES, OR THIS AGREEMENT, HOWEVER ARISING INCLUDING NEGLIGENCE, EVEN IF WE OR OUR AGENTS OR REPRESENTATIVES KNOW OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                <p>THE Raven (or Raven Platform) PLATFORM MAY BE USED BY YOU TO REQUEST AND SCHEDULE TRANSACTIONS WITH THIRD-PARTY PROVIDERS, BUT YOU AGREE THAT Raven (or Raven Platform) HAS NO RESPONSIBILITY OR LIABILITY TO YOU RELATED TO ANY TRANSACTIONS, GOODS, OR THIRD-PARTY SERVICES SET FORTH IN THIS AGREEMENT.</p>
                <p>FOR CLARITY AND WITHOUT LIMITING THE FOREGOING, Raven (or Raven Platform) HAS NO RESPONSIBILITY OR LIABILITY FOR ANY DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR RELIANCE ON TRANSACTIONS, GOODS, OR THIRD-PARTY SERVICES SET FORTH IN THIS AGREEMENT OR ANY TRANSACTION OR RELATIONSHIP BETWEEN YOU AND ANY THIRD-PARTY PROVIDER.</p>
                <p>CERTAIN JURISDICTIONS MAY NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CERTAIN DAMAGES, IN WHICH CASE THIS LIMITATION SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW.</p>

                <h2>17. No class action</h2>
                <p>You hereby waive any right to assert any claims against us as a representative or member in any class or representative action, except where such waiver is prohibited by law or is against public policy. To the extent you are permitted by law or a court of law to proceed with a class or representative action against us, you agree that: (i) you shall not be entitled to recover attorneys' fees or costs associated with pursuing the class or representative action (notwithstanding any other provision in these Terms to the contrary); and (ii) you will not submit a claim or otherwise participate in any recovery secured through the class or representative action.</p>

                <h2>18. Dispute resolution and arbitration</h2>
                <p>At our sole discretion, any dispute arising under these Terms may be required to be submitted to final and binding arbitration under the Rules of Arbitration of the Panama Arbitration Centre (Centro de Conciliación y Arbitraje de Panamá), applying the laws of Panama. Any dispute, controversy, or claim arising out of or relating to these Terms, including their breach, termination, or validity, shall be resolved by arbitration in accordance with the Swiss Rules of International Arbitration of the Panama Arbitration Centre (Centro de Conciliación y Arbitraje de Panamá). The arbitrator shall have the authority to rule on their own jurisdiction and on the validity or enforceability of any part of the arbitration agreement. The parties agree that the number of arbitrators shall be one. The seat of arbitration shall be Zurich. The proceedings shall be conducted in English. This agreement does not permit class arbitration or any claims brought as a plaintiff or class member in any class or representative arbitration proceeding. The arbitrator shall not consolidate more than one person’s claims or preside over any form of a representative or class proceeding.</p>

                <h2>19. Indemnification</h2>
                <p>To the full extent permitted by law, you agree to indemnify us, defend and hold us harmless, and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable solicitor's fees, made by any third-party due to or arising out of your breach of these Terms of Use or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.</p>

                <h2>20. Severability</h2>
                <p>If any provision (or part of a provision) of these Terms of Use is determined to be unlawful, void or unenforceable, it will nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion will be deemed to be severed from these Terms of Use. Such determination will not affect the validity and enforceability of any other remaining provisions.</p>

                <h2>21. Entire agreement</h2>
                <p>The failure of us to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision.</p>
                <p>These Terms, together with any additional terms and conditions referenced herein or made available on our website, constitute the complete and exclusive agreement between us and you with respect to the subject matter of these Terms. They supersede all prior and contemporaneous understandings, agreements, representations, and warranties, whether written or oral, regarding the subject matter. In the event of any inconsistency between the statements in these Terms and any additional terms available on our website or elsewhere, the statements in these Terms shall prevail.</p>
                <p>Any ambiguities in the interpretation of these Terms of Use will not be construed against the drafting party.</p>

                <h2>22. Governing law</h2>
                <p>All matters relating to the Websites, Services and these Terms and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the laws of Panama without giving effect to any choice or conflict of law provision or rule.</p>
                <p>Any legal suit, action, or proceeding arising out of, or related to, these Terms of Use, the Platform or Services shall be instituted exclusively in the courts of Panama, although we retain the right to bring any suit, action, or proceeding against you for breach of these Terms of Use in your country of residence or any other relevant country. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</p>

                <h2>23. Suspension and Termination</h2>
                <p>We reserve the right to suspend or limit your access to the Platform at any time, without notice, for any reason, including but not limited to compliance with legal requirements, suspicion of fraudulent activities, or breaches of these Terms of Use.</p>
                <p>We may, at our sole discretion, terminate your access to the Platform for any reason, including, if we determine that you have engaged in conduct that violates these Terms of Use, is harmful to other users of the Platform, us or third parties.</p>

                <h2>24. Service Availability and Maintenance</h2>
                <p>We strive to ensure that the Platform is available at all times, however, we do not guarantee that your access will be uninterrupted. We may perform maintenance or updates that may temporarily affect service availability. We will make reasonable efforts to inform you of any scheduled maintenance in advance.</p>

                <h2>25. Changes and Modifications</h2>
                <p>We reserve the right in our sole direction to modify, suspend, or discontinue, whether temporarily or permanently, any Service (or any features or parts thereof) at any time and without liability. You must check this page frequently so you are aware of any changes, as they are binding on you.</p>
                <p>We may release updates to the Platform from time to time to improve performance, enhance security, or add new features. These updates may be installed automatically by your browser or may require manual installation. You agree to accept and install all updates promptly to ensure the continued functionality and security of the Services.</p>
                <p>We may offer new features or tools in a beta version for testing and feedback from time to time. Such beta features are provided "as is" and may contain bugs or issues. Your use of beta features is at your own risk, and we are not liable for any issues arising from their use.</p>
                <p>Any releases, updates, or enhancements to the Service will be subject to these Terms of Use.</p>

                <h2>Annexure A - Risks</h2>
                <p>By using our Platform and Services, you acknowledge and accept the following risks. Please note that the below is not an exhaustive list of all risk, and you must take the necessary steps to inform yourself of any and all risks related to your use of the Platform and the Services.</p>

                <h3>General Risks of Digital Assets</h3>
                <p>The subjective and highly volatile nature of Digital Assets can lead to significant fluctuations at any moment, potentially resulting in them becoming worthless. These fluctuations have the potential to impact the value of your Digital Assets, including those provided through our Services. We cannot guarantee that you will not experience losses when purchasing or trading Digital Assets.</p>
                <p>Digital Assets are not legal tender and may lack backing by physical assets or guarantees from governments or centralised authorities. They may not possess intrinsic value and may have restricted circulation.</p>
                <p>Digital Assets are generally high-risk and may or may not be classified as securities in certain jurisdictions. Therefore, it's essential to exercise prudent judgment when trading Digital Assets.</p>
                <p>Digital Assets are inherently complex, characterised by terms, features, and risks that may be challenging to grasp due to their innovative and technological nature.</p>
                <p>There is no assurance that the Platform or associated Services will remain stable. The value of listed Digital Assets may undergo substantial fluctuations and could potentially become valueless.</p>
                <p>Transactions involving Digital Assets may not be protected by investor compensation funds or deposit protection schemes, leading to diminished security.</p>

                <h3>Risks Related to Transactions and Usage</h3>
                <p>Engaging with our Services may incur various fees, including those stemming from Blockchain operations, irrespective of transaction outcomes. These fees are definitive and non-reversible. It is important to comprehend all relevant fees before executing any transactions and to seek clarification if necessary.</p>
                <p>We are not responsible for determining the tax implications associated with your transactions on or through our Services. You are responsible for ascertaining any tax obligations arising from your Digital Asset transactions.</p>
                <p>Our Services do not store, send, or receive Digital Assets. Digital Assets are founded on ownership records on the Blockchain. Transfers take place within the Blockchain, not through our Services, and are documented on the public ledger, which may not correspond with the initiation time.</p>
                <p>Blockchain transactions are irreversible once confirmed. You are responsible for ensuring the accuracy of transaction details, including wallet addresses, amounts, and network selections. Any errors, including sending assets to incorrect or incompatible addresses, may result in permanent loss.</p>
                <p>The cost and speed of transacting with Blockchain-based systems are variable and may increase dramatically without warning, potentially impacting your activities on the Platform.</p>
                <p>Transactions involving peer-to-peer items created by third parties carry inherent risks, including the purchase of counterfeit or mislabelled items. Ensure you conduct thorough research before interacting with any Digital Assets.</p>

                <h3>Risks Related to Technology, Security, and Regulation</h3>
                <p>The regulatory landscape for Blockchain technologies, NFTs, and Digital Assets is subject to change and lacks clarity. Potential new regulations may have an adverse impact on our Services as well as the value and usability of Digital Assets.</p>
                <p>Beware of potential threats from malicious individuals or organisations aiming to steal your Digital Assets. Take necessary precautions to safeguard yourself against such risks.</p>
                <p>No technology is entirely immune to security vulnerabilities. You should exercise prudence when using any technology.</p>
                <p>Our Services rely on third-party smart contracts and public Blockchains. We do not own, control, or guarantee the operation, functionality, or security of these systems. Malfunctions in third-party smart contracts or delays in Blockchain operations may result in failed or delayed transactions.</p>
                <p>By using the Platform and Services, you represent that you are financially and technically sophisticated enough to understand the inherent risks of cryptographic systems, Blockchain-based networks, and Digital Assets. You acknowledge the risks of interacting with these technologies, including the potential for loss of Digital Assets due to errors, vulnerabilities, or security breaches.</p>
                <p>We cannot be held liable for any losses resulting from delays or failures reported by developers or representatives concerning any Blockchain that supports Digital Assets. This includes issues such as forks, technical node problems, or other issues.</p>
                <p>You are solely responsible for securing your private key(s). Losing control of your private key(s) will permanently deny access to your Digital Assets. Neither we nor any third party can retrieve or restore lost private key(s).</p>

                <h3>Market Risks</h3>
                <p>The markets for Digital Assets are nascent and highly volatile due to factors such as adoption, speculation, technological risks, security vulnerabilities, and regulatory uncertainty. You acknowledge the risk of trading counterfeit, mislabelled, or fake tokens, including tokens that falsely claim to represent existing projects.</p>
                <p>Stablecoins may not be fully or adequately collateralised and are subject to risks, including price volatility, panics, or liquidity issues.</p>
                <p>If you act as a liquidity provider to the Protocol, you acknowledge that your Digital Assets may lose value due to price fluctuations of tokens in trading pairs or liquidity pools.</p>

                <h3>Additional Risks</h3>
                <p>Using Internet and Blockchain-based products carries inherent risks, including but not limited to, hardware, software, and Internet connection issues, as well as the potential for malicious software and unauthorised access to your wallet address. We are not responsible for any communication failures, disruptions, errors, distortions, or delays experienced when using our Service or any Blockchain network.</p>
                <p>Our Services may depend on third-party platforms and vendors, and access to and use of the Service may be impacted if we cannot maintain relationships with these third parties. Additionally, changes in their terms or pricing, our violation of their terms, or if these parties become unavailable for any reason, can affect the availability of our Service.</p>
                <p>Certain individuals or groups may have significant control over the total supply of any Digital Assets, often referred to as "whales." These entities can have a significant impact on the market, influencing the price, value, or functionality of Digital Assets, which may not be in line with your best interests as an owner of Digital Assets.</p>
                <p>Smart contract transactions automatically execute and settle. We do not take any action to resolve erroneous trades resulting from your errors.</p>
            </div>
        </div>
    );
}
